// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBUSnh_vZ2pX7IZfRlmmMFj0868-17js',
    appId: '1:2676347504:web:82c49762031dec46c79ab5',
    messagingSenderId: '2676347504',
    projectId: 'let-s-chat-77748',
    authDomain: 'let-s-chat-77748.firebaseapp.com',
    storageBucket: 'let-s-chat-77748.appspot.com',
    measurementId: 'G-9DQQY3MZF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEh9pikww4BRRquB3Wi3_tqr_3zCEuDI4',
    appId: '1:2676347504:android:33f35719e3a80427c79ab5',
    messagingSenderId: '2676347504',
    projectId: 'let-s-chat-77748',
    storageBucket: 'let-s-chat-77748.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgv_TJPzQ1RAwsSlnYDOr6VdUPU44BeA0',
    appId: '1:2676347504:ios:1f71fdc9cc7f2577c79ab5',
    messagingSenderId: '2676347504',
    projectId: 'let-s-chat-77748',
    storageBucket: 'let-s-chat-77748.appspot.com',
    iosBundleId: 'com.siajdynamicinnovations.letschat.letsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgv_TJPzQ1RAwsSlnYDOr6VdUPU44BeA0',
    appId: '1:2676347504:ios:1f71fdc9cc7f2577c79ab5',
    messagingSenderId: '2676347504',
    projectId: 'let-s-chat-77748',
    storageBucket: 'let-s-chat-77748.appspot.com',
    iosBundleId: 'com.siajdynamicinnovations.letschat.letsChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYBUSnh_vZ2pX7IZfRlmmMFj0868-17js',
    appId: '1:2676347504:web:ddac4eecc5183a47c79ab5',
    messagingSenderId: '2676347504',
    projectId: 'let-s-chat-77748',
    authDomain: 'let-s-chat-77748.firebaseapp.com',
    storageBucket: 'let-s-chat-77748.appspot.com',
    measurementId: 'G-DQ2R2H937L',
  );
}
