// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFGTXUSHOues8_cHroaPYNZzpKvvk0Wt0',
    appId: '1:63457668790:web:145df79b305a72718e0017',
    messagingSenderId: '63457668790',
    projectId: 'lets-talk-9b2f8',
    authDomain: 'lets-talk-9b2f8.firebaseapp.com',
    storageBucket: 'lets-talk-9b2f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPy7HXzmw6NR8j0PI3Qbty5KzqhdS1Axk',
    appId: '1:63457668790:android:9fa1cf7bf12ee78f8e0017',
    messagingSenderId: '63457668790',
    projectId: 'lets-talk-9b2f8',
    storageBucket: 'lets-talk-9b2f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-00cDJzhE5L5jcPAV8k3BNMTZIwfbQWI',
    appId: '1:63457668790:ios:7e737a6592b48cff8e0017',
    messagingSenderId: '63457668790',
    projectId: 'lets-talk-9b2f8',
    storageBucket: 'lets-talk-9b2f8.appspot.com',
    iosBundleId: 'com.siajdynamicinnovations.letschat.letsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-00cDJzhE5L5jcPAV8k3BNMTZIwfbQWI',
    appId: '1:63457668790:ios:7e737a6592b48cff8e0017',
    messagingSenderId: '63457668790',
    projectId: 'lets-talk-9b2f8',
    storageBucket: 'lets-talk-9b2f8.appspot.com',
    iosBundleId: 'com.siajdynamicinnovations.letschat.letsChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFGTXUSHOues8_cHroaPYNZzpKvvk0Wt0',
    appId: '1:63457668790:web:7f499068a9beed6c8e0017',
    messagingSenderId: '63457668790',
    projectId: 'lets-talk-9b2f8',
    authDomain: 'lets-talk-9b2f8.firebaseapp.com',
    storageBucket: 'lets-talk-9b2f8.appspot.com',
  );
}
